# Generated by Django 5.1.6 on 2025-03-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='moduleinstance',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='myapp.module'),
        ),
        migrations.AlterField(
            model_name='moduleinstance',
            name='professors',
            field=models.ManyToManyField(related_name='module_instances', to='myapp.professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
